### ISSUE TITLE
keep all cost info if possible and attach cost info to product barcode

### ISSUE THREAD

**Issue by ThijmenGThN** [ThijmenGThN/ThijmenHeuvelink.nl#1]

**Comment by ThijmenGThN** [comment]
![Image](https://user-images.githubusercontent.com/54316157/207809282-b65852de-3c4f-4579-8d32-2a6476b516f0.png)

This is all the data I'm able to work with.

```
Shipment_Due_Date
Due_Date_Compliance
My_Shipment_Name
PO_Number
DC Building
Status
Product_Title
SKU
TSIN
Qty_Required
Qty_Sent
Qty_Received
Qty_Damaged
```

Attach, cost? to, barcode? 😅 

I'm a bit puzzled on what you need exactly, could you go in depth of what's actually needed?

**Comment by Faarhan01** [comment]
TSIN is the barcode if im not wrong, i meant keep info on the cost price added attached to a certain TSIN if possible. We can skip this though if it still doesnt make sense

**Comment by ThijmenGThN** [comment]
There's a difference between them based on your pdf.

![image](https://user-images.githubusercontent.com/54316157/207835727-7af51725-2b6d-4936-9f39-c743f1238656.png)

But, if I'm assuming correctly; you just need to save the cost price (set by you) as part of a product.

**Comment by Faarhan01** [comment]
yes, you are right, attach to TSIN pls since i wouldnt have to manually add the cost price to products if i delete them again

**Comment by ThijmenGThN** [comment]
Okay, so the price is linked to a TSIN, which reflects on all products with the same TSIN.

Right?

**Comment by Faarhan01** [comment]
I think all products have different TSIN, if thats the case then yes, have you come across any products that had the same one?

**Comment by ThijmenGThN** [comment]
Many are the same actually.

![Image](https://user-images.githubusercontent.com/54316157/207841334-54aa691e-e0af-4609-86f3-a8b9a41a2a87.png)

**Comment by Faarhan01** [comment]
Okay so barcode then?

**Comment by ThijmenGThN** [comment]
There isn't one in the excels you've sent.

**Comment by ThijmenGThN** [comment]
![Image](https://user-images.githubusercontent.com/54316157/207841952-7c51e8ad-e723-4514-8dd1-fb8ebaa8eefd.png)

**Comment by Faarhan01** [comment]
alright lets skip then since it only shows up in the pdf
