### ISSUE TITLE
clear all button = clears all current products (should have a safety feature like "are you sure" and double click

### ISSUE THREAD

**Issue by ThijmenGThN** [ThijmenGThN/ThijmenHeuvelink.nl#2]

**Comment by ThijmenGThN** [comment]
So, basically.. a delete all from this section button.

Or

Is a single button in the "all products" section which deletes everything at once, fine?

**Comment by Faarhan01** [comment]
Should be in dashboard

**Comment by ThijmenGThN** [comment]
Just a simple, delete all button in the dashboard?

Like so:
![image](https://user-images.githubusercontent.com/54316157/207835392-3b83f4e5-94a9-40d3-8155-6f36e3b40216.png)

**Comment by Faarhan01** [comment]
yes
