### ISSUE TITLE
No price section = This section just shows products which i have not added a cost price for, once i do add a price it automatically gets removed from this section

### ISSUE THREAD

**Issue by ThijmenGThN** [ThijmenGThN/ThijmenHeuvelink.nl#3]

**Comment by ThijmenGThN** [comment]
Cool, got it.

Where should you be able to see the cost price though?


![Image](https://user-images.githubusercontent.com/54316157/207808365-78c5062d-861a-4f84-b0a0-e329d7032574.png)

Like so?

**Comment by Faarhan01** [comment]
Yes

**Comment by ThijmenGThN** [comment]
Great, I'll get started on that.
